//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptikOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHIZLIURUN
    {
        public int id { get; set; }
        public string Barkod { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    }
}
