//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptikOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        public int UrunId { get; set; }
        public string Barkod { get; set; }
        public string UrunAd { get; set; }
        public string Aciklama { get; set; }
        public string UrunGrup { get; set; }
        public Nullable<decimal> AlisFiyat { get; set; }
        public Nullable<decimal> SatisFiyat { get; set; }
        public Nullable<int> KdvOrani { get; set; }
        public Nullable<decimal> KdvTutari { get; set; }
        public string Birim { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kullanici { get; set; }
    }
}
